from tkinter import *
def Eng():
    E = Tk()
    E.geometry("1000x600")
    E.configure(bg='#0c97e8')
    E_l = Label(E, text="Enter Your 4 digit PIN number", font=('Unbounded', 40), bg='#0c97e8')
    E_l.pack(pady=40)
    In_var = IntVar()
    In = Entry(E, textvariable=In_var, font=('Unbounded', 40),width=5,bg='#0c97e8')
    In.pack()
    #frame = Frame(E,borderwidth=10,relief=SOLID,pady=20,padx=100)
    B1 = Button(E,text="WITHDRAWL",font=('Roboto',30))
    B1.pack(padx=20,pady=2,)
    B1 = Button(E, text="BALANCE",font=('Roboto',30))
    B1.pack(padx=20,pady=20)
    B1 = Button(E, text="CASH DEPOSIT",font=('Roboto',30))
    B1.pack(padx=20,pady=20)
    B1 = Button(E, text="PIN CHANGE",font=('Roboto',30))
    B1.pack(padx=20,pady=20)
    #frame.pack(anchor='center',pady=50)
    E.mainloop()
